## Import Libraries

In [2]:
## For loading and preprocessing
import pandas as pd
import numpy as np

## For data visualization
import matplotlib.pyplot as plt
import seaborn as sns

## Loading Data & Creating Copy

In [3]:
data=pd.read_csv('Dataset/car_price_prediction.csv')

In [4]:
df= data.copy()

## DataPreview And Understanding 

In [5]:
## View the first raws
df.head()

ID  Price  Levy Manufacturer    Model  Prod. year   Category  \
0  45654403  13328  1399        LEXUS   RX 450        2010       Jeep   
1  44731507  16621  1018    CHEVROLET  Equinox        2011       Jeep   
2  45774419   8467     -        HONDA      FIT        2006  Hatchback   
3  45769185   3607   862         FORD   Escape        2011       Jeep   
4  45809263  11726   446        HONDA      FIT        2014  Hatchback   

  Leather interior Fuel type Engine volume    Mileage  Cylinders  \
0              Yes    Hybrid           3.5  186005 km        6.0   
1               No    Petrol             3  192000 km        6.0   
2               No    Petrol           1.3  200000 km        4.0   
3              Yes    Hybrid           2.5  168966 km        4.0   
4              Yes    Petrol           1.3   91901 km        4.0   

  Gear box type Drive wheels   Doors             Wheel   Color  Airbags  
0     Automatic          4x4  04-May        Left wheel  Silver       12  
1     Tiptronic          4x4  04-May        Left wheel   Black        8  
2      Variator        Front  04-May  Right-hand drive   Black        2  
3     Automatic          4x4  04-May        Left wheel   White        0  
4     Automatic        Front  04-May        Left wheel  Silver        4

In [6]:
## View the last five rows
df.tail()

ID  Price  Levy   Manufacturer    Model  Prod. year Category  \
19232  45798355   8467     -  MERCEDES-BENZ  CLK 200        1999    Coupe   
19233  45778856  15681   831        HYUNDAI   Sonata        2011    Sedan   
19234  45804997  26108   836        HYUNDAI   Tucson        2010     Jeep   
19235  45793526   5331  1288      CHEVROLET  Captiva        2007     Jeep   
19236  45813273    470   753        HYUNDAI   Sonata        2012    Sedan   

      Leather interior Fuel type Engine volume    Mileage  Cylinders  \
19232              Yes       CNG     2.0 Turbo  300000 km        4.0   
19233              Yes    Petrol           2.4  161600 km        4.0   
19234              Yes    Diesel             2  116365 km        4.0   
19235              Yes    Diesel             2   51258 km        4.0   
19236              Yes    Hybrid           2.4  186923 km        4.0   

      Gear box type Drive wheels   Doors       Wheel   Color  Airbags  
19232        Manual         Rear  02-Mar  Left wheel  Silver        5  
19233     Tiptronic        Front  04-May  Left wheel     Red        8  
19234     Automatic        Front  04-May  Left wheel    Grey        4  
19235     Automatic        Front  04-May  Left wheel   Black        4  
19236     Automatic        Front  04-May  Left wheel   White       12

In [7]:
## Check the number of rows and colums
print(f'Total number of rows: {df.shape[0]} -> Total number of colums: {df.shape[1]}')


Total number of rows: 19237 -> Total number of colums: 18


In [8]:
## Get a summary description of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                19237 non-null  int64  
 1   Price             19237 non-null  int64  
 2   Levy              19237 non-null  object 
 3   Manufacturer      19237 non-null  object 
 4   Model             19237 non-null  object 
 5   Prod. year        19237 non-null  int64  
 6   Category          19237 non-null  object 
 7   Leather interior  19237 non-null  object 
 8   Fuel type         19237 non-null  object 
 9   Engine volume     19237 non-null  object 
 10  Mileage           19237 non-null  object 
 11  Cylinders         19237 non-null  float64
 12  Gear box type     19237 non-null  object 
 13  Drive wheels      19237 non-null  object 
 14  Doors             19237 non-null  object 
 15  Wheel             19237 non-null  object 
 16  Color             19237 non-null  object

In [9]:
## Checking for missing values
df.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64

In [10]:
## Checking for duplicated values
df.duplicated().sum()

313

In [11]:
## Looking for unique instances in the columns
print(np.unique(df['Price']))

[       1        3        6 ...   627220   872946 26307500]


In [12]:
print(np.unique(df['Levy']))

['-' '1011' '1016' '1017' '1018' '1024' '1028' '1030' '1031' '1032' '1036'
 '1039' '1045' '1047' '1051' '1053' '1054' '1055' '1058' '1062' '1064'
 '1076' '1077' '1079' '1080' '1083' '1086' '1090' '1091' '1094' '1095'
 '1099' '1103' '1104' '1107' '1108' '1109' '1110' '1111' '1113' '1118'
 '1132' '1138' '1141' '1148' '115' '1156' '1163' '11706' '1171' '11714'
 '1172' '1174' '1176' '1178' '1185' '1187' '1190' '1194' '1195' '1197'
 '1198' '1202' '1203' '1205' '1211' '1228' '1234' '1236' '1246' '1249'
 '1252' '1266' '1267' '1268' '1272' '1273' '1275' '1277' '1279' '1282'
 '1285' '1286' '1288' '1292' '1296' '1297' '1301' '1304' '1307' '1308'
 '1317' '1323' '1324' '1325' '1327' '1341' '1342' '1345' '1346' '1347'
 '1356' '1357' '1360' '1361' '1363' '1365' '1366' '1368' '1369' '1375'
 '1384' '1387' '1391' '1399' '1405' '1408' '1411' '1413' '1426' '1436'
 '1437' '1438' '1440' '1441' '1442' '1451' '1452' '1466' '1468' '1470'
 '1473' '1474' '1481' '1482' '1486' '1488' '1493' '1502' '1503' '1505'
 

In [29]:
data=pd.read_csv('Dataset/car_price_prediction.csv', na_values=['-'])

In [30]:
data.isnull().sum()

ID                     0
Price                  0
Levy                5819
Manufacturer           0
Model                  0
Prod. year             0
Category               0
Leather interior       0
Fuel type              0
Engine volume          0
Mileage                0
Cylinders              0
Gear box type          0
Drive wheels           0
Doors                  0
Wheel                  0
Color                  0
Airbags                0
dtype: int64

In [31]:
## Replacing Missing Values

print(np.unique(data['Levy']))

[   87.   115.   155.   167.   173.   175.   247.   259.   271.   279.
   289.   294.   308.   328.   333.   345.   353.   362.   363.   364.
   382.   394.   397.   399.   400.   402.   418.   419.   420.   421.
   424.   425.   426.   431.   441.   442.   446.   447.   448.   456.
   460.   461.   462.   463.   473.   474.   475.   481.   488.   489.
   490.   494.   501.   502.   503.   505.   517.   518.   521.   524.
   526.   527.   528.   530.   531.   551.   552.   556.   557.   562.
   565.   574.   579.   583.   584.   585.   586.   595.   603.   604.
   605.   607.   609.   612.   614.   617.   623.   626.   627.   629.
   636.   637.   638.   639.   640.   641.   642.   644.   645.   649.
   650.   658.   663.   666.   668.   676.   681.   682.   683.   686.
   687.   690.   691.   692.   694.   695.   696.   697.   702.   706.
   707.   714.   722.   723.   724.   729.   730.   731.   732.   738.
   741.   742.   746.   748.   749.   750.   751.   753.   760.   761.
   764

In [13]:
print(np.unique(df['Manufacturer']))

['ACURA' 'ALFA ROMEO' 'ASTON MARTIN' 'AUDI' 'BENTLEY' 'BMW' 'BUICK'
 'CADILLAC' 'CHEVROLET' 'CHRYSLER' 'CITROEN' 'DAEWOO' 'DAIHATSU' 'DODGE'
 'FERRARI' 'FIAT' 'FORD' 'GAZ' 'GMC' 'GREATWALL' 'HAVAL' 'HONDA' 'HUMMER'
 'HYUNDAI' 'INFINITI' 'ISUZU' 'JAGUAR' 'JEEP' 'KIA' 'LAMBORGHINI' 'LANCIA'
 'LAND ROVER' 'LEXUS' 'LINCOLN' 'MASERATI' 'MAZDA' 'MERCEDES-BENZ'
 'MERCURY' 'MINI' 'MITSUBISHI' 'MOSKVICH' 'NISSAN' 'OPEL' 'PEUGEOT'
 'PONTIAC' 'PORSCHE' 'RENAULT' 'ROLLS-ROYCE' 'ROVER' 'SAAB' 'SATURN'
 'SCION' 'SEAT' 'SKODA' 'SSANGYONG' 'SUBARU' 'SUZUKI' 'TESLA' 'TOYOTA'
 'UAZ' 'VAZ' 'VOLKSWAGEN' 'VOLVO' 'ZAZ' 'სხვა']


In [14]:
print(np.unique(df['Prod. year']))

['09-Mar' '100' '100 NX' ... 'macan S' 'tC' 'xD']


In [15]:
print(np.unique(df['Prod. year']))

[1939 1943 1947 1953 1957 1964 1965 1968 1973 1974 1976 1977 1978 1980
 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994
 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008
 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]


In [16]:
print(np.unique(df['Category']))

['Cabriolet' 'Coupe' 'Goods wagon' 'Hatchback' 'Jeep' 'Limousine'
 'Microbus' 'Minivan' 'Pickup' 'Sedan' 'Universal']


In [17]:
print(np.unique(df['Leather interior']))

['No' 'Yes']


In [18]:
print(np.unique(df['Fuel type']))

['CNG' 'Diesel' 'Hybrid' 'Hydrogen' 'LPG' 'Petrol' 'Plug-in Hybrid']


In [19]:
print(np.unique(df['Engine volume']))

['0' '0.1' '0.2' '0.2 Turbo' '0.3' '0.3 Turbo' '0.4' '0.4 Turbo' '0.5'
 '0.6' '0.6 Turbo' '0.7' '0.7 Turbo' '0.8' '0.8 Turbo' '0.9' '1'
 '1.0 Turbo' '1.1' '1.1 Turbo' '1.2' '1.2 Turbo' '1.3' '1.3 Turbo' '1.4'
 '1.4 Turbo' '1.5' '1.5 Turbo' '1.6' '1.6 Turbo' '1.7' '1.7 Turbo' '1.8'
 '1.8 Turbo' '1.9' '1.9 Turbo' '2' '2.0 Turbo' '2.1' '2.1 Turbo' '2.2'
 '2.2 Turbo' '2.3' '2.3 Turbo' '2.4' '2.4 Turbo' '2.5' '2.5 Turbo' '2.6'
 '2.7' '2.7 Turbo' '2.8' '2.8 Turbo' '2.9' '2.9 Turbo' '20' '3'
 '3.0 Turbo' '3.1' '3.2' '3.2 Turbo' '3.3' '3.4' '3.5' '3.5 Turbo' '3.6'
 '3.6 Turbo' '3.7' '3.7 Turbo' '3.8' '3.9' '4' '4.0 Turbo' '4.2'
 '4.2 Turbo' '4.3' '4.4' '4.4 Turbo' '4.5' '4.5 Turbo' '4.6' '4.6 Turbo'
 '4.7' '4.7 Turbo' '4.8' '4.8 Turbo' '5' '5.0 Turbo' '5.2' '5.3' '5.4'
 '5.4 Turbo' '5.5' '5.5 Turbo' '5.6' '5.7' '5.7 Turbo' '5.8' '5.9' '6'
 '6.2' '6.3' '6.3 Turbo' '6.4' '6.7' '6.8' '7.3']


In [20]:
print(np.unique(df['Mileage']))

['0 km' '1000 km' '10000 km' ... '99999 km' '999999 km' '999999999 km']


In [21]:
print(np.unique(df['Cylinders']))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 12. 14. 16.]


In [22]:
print(np.unique(df['Gear box type']))

['Automatic' 'Manual' 'Tiptronic' 'Variator']


In [23]:
print(np.unique(df['Doors']))

['02-Mar' '04-May' '>5']


In [24]:
print(np.unique(df['Drive wheels']))

['4x4' 'Front' 'Rear']


In [25]:
print(np.unique(df['Wheel']))


['Left wheel' 'Right-hand drive']


In [26]:
print(np.unique(df['Color']))

['Beige' 'Black' 'Blue' 'Brown' 'Carnelian red' 'Golden' 'Green' 'Grey'
 'Orange' 'Pink' 'Purple' 'Red' 'Silver' 'Sky blue' 'White' 'Yellow']


In [27]:
print(np.unique(df['Airbags']))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [28]:
## Checking types on columns
df.dtypes

ID                    int64
Price                 int64
Levy                 object
Manufacturer         object
Model                object
Prod. year            int64
Category             object
Leather interior     object
Fuel type            object
Engine volume        object
Mileage              object
Cylinders           float64
Gear box type        object
Drive wheels         object
Doors                object
Wheel                object
Color                object
Airbags               int64
dtype: object